# Generated by Django 4.2.7 on 2023-11-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('BotID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('MeetingTitle', models.CharField(max_length=255, null=True)),
                ('VideoURL', models.URLField(max_length=2000, null=True)),
                ('RetentionEnd', models.DateTimeField(null=True)),
                ('CreateTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptMessage',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BotNum', models.CharField(max_length=255)),
                ('Speaker', models.CharField(max_length=255)),
                ('TimeStamp', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Message', models.CharField(max_length=9999)),
            ],
        ),
    ]
